apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-argocd
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
      - name: private-ecr
      containers:
      - name: app
        image: 469123920517.dkr.ecr.ap-southeast-1.amazonaws.com/lab-argocd:0.1.0
        ports:
        - containerPort: 80

