apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lab-applicationset
spec:
  generators:
  - matrix:
      generators:
      - list:
          elements:
          - env: dev
          - env: prd
      - git:
          repoURL: https://github.com/fpiyapol/lab-argocd.git
          revision: HEAD
          directories:
          - path: applicationset/apps/*
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/fpiyapol/lab-argocd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}-{{env}}'
      syncPolicy:
        automated: {}
